# MySQL8 설정
spring:
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: ENC(TNWd0a695QHo3kVGfM38nx092Hx/u1n8TyDyNgP/WTWQ0h3h+HTV299JgpKKVlZn8f/NVwnXmQVN64da81lE4EGXv9qHgCRtj9/dhRlpFF+VtA+Ks8imNcaBXt5KThb0JqQuAOcoPZ4D7I+aohcWQuE1IJ5mOePolvCOMLxhYSKGn++77jdjsYwADAMWHXbZeRWoOI/CbLM=)
    username: ENC(mNmhKjCACY10khaXSzlDPw==)
    password: ENC(s45rHrvYh3PvvjP1mOfxszoDaiaqwDM3)

# 콘솔에 SQL 출력 여부
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
# hibernate 설정
    database : mysql
    hibernate.ddl-auto : update
    hibernate.naming.strategy : org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true

# PostgreSQL 연동
# spring.datasource.url=jdbc:postgresql://localhost:5432/DB이름
# spring.datasource.username=postgresql_사용자명
# spring.datasource.password=postgresSql_비밀번호

# spring.datasource.data=classpath:/data.sql
# spring.datasource.initializaion-mode=always
# spring.jpa.hibernate.ddl-auto=create-drop

